services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  translation_activator:
    class: WebEtDesign\UserBundle\Security\RoleActivator
    arguments: [ "@security.authorization_checker" ]

  WebEtDesign\UserBundle\:
    resource: '../src'
    exclude:
      - '../Entity'

#  WebEtDesign\UserBundle\Security\AdminFormLoginAuthenticator: ~

  WebEtDesign\UserBundle\Controller\:
    resource: '../src/Controller/'
    tags: [ 'controller.service_arguments' ]

  # Service Roles User
  WebEtDesign\UserBundle\Handler\VoterSecurityHandler:
    arguments:
      - '@security.authorization_checker'
      - [ ROLE_SUPER_ADMIN ]

  WebEtDesign\UserBundle\Services\EditableRolesBuilder:
    arguments:
      - '@security.token_storage'
      - '@security.authorization_checker'
      - '@sonata.admin.pool'
      - '%security.role_hierarchy.roles%'
    calls:
      - [ setTranslator, [ '@translator' ] ]

  sonata.admin.security.handler.role.class:
    class: WebEtDesign\UserBundle\Handler\VoterSecurityHandler

  # Sonata admin
  WebEtDesign\UserBundle\Exporter\ExporterSonataMedia:
    autowire:      true
    autoconfigure: true


  ################################> Vich <#################################
  WebEtDesign\RgpdBundle\Exporter\ExporterVich:
    autowire:      true
    autoconfigure: true

  WebEtDesign\RgpdBundle\Anonymizer\AnonymizerVich:
    autowire:      true
    autoconfigure: true
  ################################> Vich <#################################
