services:
  _defaults:
    autowire:      true
    autoconfigure: true

  wd.user.admin.user:
    class: WebEtDesign\UserBundle\Admin\User\UserAdmin
    tags:
      - { name: sonata.admin, model_class: '%wd_user.user.class%', manager_type: orm, group: 'Utilisateur', label: Utilisateurs, label_translator_strategy: sonata.admin.label.strategy.underscore, icon: ~, default: true }
    calls:
      - [ setUserPasswordHasher, [ '@security.user_password_hasher' ] ]
      - [ setTranslationDomain, [ 'UserAdmin'] ]
    public: true

  wd.user.admin.group:
    class: WebEtDesign\UserBundle\Admin\User\GroupAdmin
    tags:
      - { name: sonata.admin, model_class: '%wd_user.group.class%', manager_type: orm, group: 'Utilisateur', label: Groupes, label_translator_strategy: sonata.admin.label.strategy.underscore }
    calls:
      - [ setTranslationDomain, [ 'GroupAdmin' ] ]
      - [ setFormTheme, [ ['@@WDUser/admin/CRUD/group/form/roles.html.twig'] ] ]
    public: true

